server.port : 8081
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
#      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/users_database
    username: root
    password: admin123